### PR TITLE
Feature/494/demo ar workflows ansible

### LINKED ISSUE #494: [FEATURE] Ansible auto remediation use case based on DT AutomationEngine
**Is your feature request related to a problem? Please describe.**
A demo use case shall be implemented based on DT AutomationEngine and Ansible (Tower/AWX).

### PR DESCRIPTION
**Pull request by tobigremmer-dt**
REsolves #494

### CODE REVIEW

**Review by drqc — COMMENTED** [review]
I started reviewing the use case by running it but I found an error, from what i understand it's related to the ownership configuration already being present. Since we no longer can recreate fresh environment each time, can we fix this so it works on environments that previously had some configurations
image

**Comment by tobigremmer-dt** [comment]
> I started reviewing the use case by running it but I found an error, from what i understand it's related to the ownership configuration already being present. Since we no longer can recreate fresh environment each time, can we fix this so it works on environments that previously had some configurations
> image

After investigating, this only applies to settings 2.0 objects that were created earlier that now contain conflicting attributes, e.g. ownership identifier. As this only happens during development, I suggest we ignore this for now. Any breaking changes later have to safeguard this behavior, e.g. by deleting the settings object first.

**Review by drqc — APPROVED** [review]
lgtm, i tested it and it works end 2 end after removing the previous ownership configuration

**Comment by drqc** [comment]
About the debounce workflow, is this something that would always be needed or just something until Dynatrace Events are more detailed?

**Comment by tobigremmer-dt** [comment]
> About the debounce workflow, is this something that would always be needed or just something until Dynatrace Events are more detailed?

Correct. Debounce workflow can be removed as soon as there is a concept of a problem being reopened in order to trigger the workflow not only on the first occurrence of an issue.

**Pull request merged**
