### PR TITLE
Feature/611/demo all validation

### LINKED ISSUE #611: [FEATURE] demo-all nightly validation
**Is your feature request related to a problem? Please describe.**
demo-all nightly demo runs shall be automatically validated.

### PR DESCRIPTION
**Pull request by tobigremmer-dt**
Resolves #611

### CODE REVIEW

**Comment by tobigremmer-dt** [comment]
TBD:
- [x] Docs for ensure-notebook.yml and delete-notebook.yml

**Review by drqc — APPROVED** [review]
lgtm. Just one observation for the are_nightly_auto_runs_enabled part, can you add more docs maybe on the next PR. So it explains where to check the validation and if you are using an email  to alert the status maybe provide a email var

**Comment by tobigremmer-dt** [comment]
As discussed with team, email notifications shall be implemented as a first step.

**Comment by tobigremmer-dt** [comment]
Added comment to https://github.com/Dynatrace/ace-box/issues/611 . Closing this PR for now.

**Pull request closed without merging**
