### PR TITLE
Update sli definition and pipeline labels for ace-demo

### LINKED ISSUE #150: [BUG] Quality gates ace-demo broken
Ace demo is broken for keptn and quality gates, the labels are missing for the SLI. The expected label is DT_APPLICATION_RELEASE_VERSION. The application under Dynatrace is  DT_RELEASE_VERSION. Which one should be fixed? the SLI file? or the Dynatrace env tags?

### PR DESCRIPTION
**Pull request by drqc**
fixes #150 .

### CODE REVIEW

**Review by kristofre — DISMISSED** [review]

**Review by kristofre — COMMENTED** [review]
please fix the other pipelines as well

**Comment by kristofre** [comment]
@drqc there are also other files that need to be changed like dynatrace.conf.yaml and within the pipeline the attachrules

**Comment by kristofre** [comment]
@drqc can you also look at the appsec jenkinsfile? we need to ensure those usecases work before generating a new release.

**Review by tobigremmer-dt — APPROVED** [review]
Looks good

**Pull request merged**
