### PR TITLE
add otel_export_enable to aws and azure

### LINKED ISSUE #726: [BUG] OpenTelemetry export fails on AWS and Azure terraform
The variable propagation for `otel_export_enable` is not set up for AWS and Azure

This causes the TF scripts to fail on those hyperscalers

### PR DESCRIPTION
**Pull request by kristofre**
Closes #726

### CODE REVIEW

**Comment by kristofre** [comment]
@eemrdog @IgnacioGoldman @drqc @Eugenio-DT I do not have AWS or Azure set up. Can you test this branch and let me know if it now works?

Thanks!

**Comment by amohrd** [comment]
- Enhancements for otel : terraform plan and apply looks good (tested: Azure) 
- It looks like Terraform provider azurerm > 4.0 requires subscription_id. Adding the following line in terraform/azure/main.tf solves the issue for me now

```
provider "azurerm" {
    features {}
    subscription_id = "7e2d5dfa-86a1-46e8-b51d-609b547112ae" 
}
```


image

**Comment by eemrdog** [comment]
@amohrd I have added subscription_id parameter with the provider versions. Can you test this version for your provisioning?

**Comment by kristofre** [comment]
Is this one good to merge or do we need further testing?

**Review by eemrdog — APPROVED** [review]
looks good! I have tested aws and it worked. Azure also worked with another contact´s test

**Pull request merged**
