### PR TITLE
Unguard updates

### LINKED ISSUE #352: [FEATURE] Update unguard to latest version and adapt helm chart
Unguard has seen new versions being released.
We need to adapt the helm chart - which has introduced new services - to deploy these services.

New services added:
- malicious-load-generator
- profile-service
- status-service

### PR DESCRIPTION
**Pull request by anton-fre**
This pull request closes issue #352

### CODE REVIEW

**Comment by kristofre** [comment]
I spoke to @anton-freyberg about needed changes that he will implement later this week. added wip label for now

**Review by kristofre — APPROVED** [review]

**Comment by kristofre** [comment]
Update: still need to update the role main.yml

**Review by kristofre — CHANGES_REQUESTED** [review]
must update main.yml of role to incorporate new helm values

**Comment by anton-fre** [comment]
added the right variables.

**Review by kristofre — APPROVED** [review]

**Pull request merged**
